return {
    SYNTAXES = {
        plaintext = "Plain text",
        bash = "Bash",
        c = "C",
        cmake = "CMake",
        cpp = "C++",
        crystal = "Crystal",
        cs = "C#",
        d = "D",
        dart = "Dart",
        django = "Django Template",
        dockerfile = "Dockerfile",
        elixir = "Elixir",
        golang = "Golang",
        html = "HTML",
        java = "Java",
        javascript = "Javascript",
        julia = "Julia",
        json = "JSON",
        kotlin = "Kotlin",
        lua = "Lua",
        makefile = "Makefile",
        markdown = "Markdown",
        nginx = "nginx.conf",
        protobuf = "Protobuf",
        python = "Python",
        ruby = "Ruby",
        rust = "Rust",
        sh = "Shell Script",
        sql = "SQL",
        toml = "TOML",
        ts = "Typescript",
        yaml = "YAML"
    }
}
